"""A module to run sse job on OQTOPUS Cloud."""

import base64
from pathlib import Path, PurePath

from quri_parts.backend import BackendError
from typing_extensions import deprecated

from quri_parts_oqtopus.backend.config import OqtopusConfig
from quri_parts_oqtopus.backend.jobs.base import OqtopusJobBackendBase
from quri_parts_oqtopus.models.jobs.sse import OqtopusSseJob
from quri_parts_oqtopus.rest import (
    JobsSubmitJobInfo,
    JobsSubmitJobRequest,
)


class OqtopusSseBackend(OqtopusJobBackendBase):
    """A job for a SSE.

    Args:
        config: A :class:`OqtopusConfig` for job execution.

    """

    def __init__(self, config: OqtopusConfig | None = None) -> None:
        super().__init__(config=config)

    def run_sse(
        self,
        file_path: str,
        device_id: str,
        name: str,
        description: str | None = None,
    ) -> OqtopusSseJob:
        """Perform a SSE job.

        Args:
            file_path (str): The path to program file to upload.
            device_id (str): The identifier of the device where the job is executed.
            name (str): The name of the job.
            description (str | None, optional): The description of the job.
                Defaults to None.

        Raises:
            ValueError: If ``file_path`` is not set.
            ValueError: If ``file_path`` does not exist.
            ValueError: If ``file_path`` is not a python file.
            ValueError: If file size is larger than max file size
            BackendError: If an error is returned from OQTOPUS Cloud.

        Returns:
            OqtopusSseJob: The job to be executed.

        """
        # if file_path is not set, raise ValueError
        if file_path is None:
            msg = "file_path is not set."
            raise ValueError(msg)

        # if the file does not exist, raise ValueError
        if not Path(file_path).exists():
            msg = f"The file does not exist: {file_path}"
            raise ValueError(msg)

        # get the base name and the extension of the file
        ext = PurePath(file_path).suffix

        # if the extension is not .py, raise ValueError
        if ext != ".py":
            msg = f"The file is not python file: {file_path}"
            raise ValueError(msg)

        with Path(file_path).open(mode="rb") as f:
            encoded = base64.b64encode(f.read())

        max_file_size = 10 * 1024 * 1024  # 10MB

        # if the file size is larger than max_file_size, raise ValueError
        if len(encoded) >= max_file_size:
            msg = f"size of the base64 encoded file is larger than {max_file_size}"
            raise ValueError(msg)

        try:
            job_info = JobsSubmitJobInfo(program=[encoded.decode("utf-8")])
            body = JobsSubmitJobRequest(
                name=name,
                description=description,
                device_id=device_id,
                job_type="sse",
                job_info=job_info,
                transpiler_info={},
                simulator_info={},
                mitigation_info={},
                shots=1,
            )
            response_submit_job = self._job_api.submit_job(body=body)
            response = self._job_api.get_job(response_submit_job.job_id)
            self.job = OqtopusSseJob(job=response, job_api=self._job_api)
        except Exception as e:
            msg = "To perform sse on OQTOPUS Cloud is failed."
            raise BackendError(msg) from e

        return self.job

    @deprecated(
        "OqtopusSseBackend().download_log is deprecated. "
        "Use `download_log` method of `OqtopusSseJob` instead. \n"
        "e.g. `OqtopusSseBackend().run_sse(...).download_log(...)` or "
        "`OqtopusJobBackendBase().retrieve_job(job_id=...).download_log(...)`"
    )
    def download_log(
        self,
        job_id: str | None = None,
        save_dir: str | None = None,
    ) -> str:
        """Download logs generated by an SSE job on a OQTOPUS Cloud.

        Args:
            job_id (str | None, optional): job id. Defaults to None.
            save_dir (str | None, optional): Local directory path for downloads.
                Defaults to None.

        Returns:
            str: The file path of the saved SSE log.

        Raises:
            ValueError: If ``job_id`` is not set and no job has been executed.
            TypeError: If the job with the given ``job_id`` is not an SSE job

        """
        if job_id is not None:
            self.job = self.retrieve_job(job_id=job_id)
        elif self.job is None:
            msg = "job_id is not set and no job has been executed."
            raise ValueError(msg)

        if not isinstance(self.job, OqtopusSseJob):
            msg = f"The job with id {job_id} is not an SSE job."
            raise TypeError(msg)

        return self.job.download_log(save_dir=save_dir)
