# coding: utf-8

# flake8: noqa
"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


if __import__("typing").TYPE_CHECKING:
    # import models into model package
    from quri_parts_oqtopus.rest.models.announcements_get_announcement_response import AnnouncementsGetAnnouncementResponse
    from quri_parts_oqtopus.rest.models.announcements_get_announcements_list_response import AnnouncementsGetAnnouncementsListResponse
    from quri_parts_oqtopus.rest.models.api_token_api_token import ApiTokenApiToken
    from quri_parts_oqtopus.rest.models.devices_device_info import DevicesDeviceInfo
    from quri_parts_oqtopus.rest.models.error_bad_request import ErrorBadRequest
    from quri_parts_oqtopus.rest.models.error_forbidden_error import ErrorForbiddenError
    from quri_parts_oqtopus.rest.models.error_internal_server_error import ErrorInternalServerError
    from quri_parts_oqtopus.rest.models.error_not_found_error import ErrorNotFoundError
    from quri_parts_oqtopus.rest.models.error_unauthorized_error import ErrorUnauthorizedError
    from quri_parts_oqtopus.rest.models.jobs_estimation_result import JobsEstimationResult
    from quri_parts_oqtopus.rest.models.jobs_get_job_status_response import JobsGetJobStatusResponse
    from quri_parts_oqtopus.rest.models.jobs_get_jobs_response import JobsGetJobsResponse
    from quri_parts_oqtopus.rest.models.jobs_get_sselog_response import JobsGetSselogResponse
    from quri_parts_oqtopus.rest.models.jobs_job_def import JobsJobDef
    from quri_parts_oqtopus.rest.models.jobs_job_info import JobsJobInfo
    from quri_parts_oqtopus.rest.models.jobs_job_result import JobsJobResult
    from quri_parts_oqtopus.rest.models.jobs_job_status import JobsJobStatus
    from quri_parts_oqtopus.rest.models.jobs_job_type import JobsJobType
    from quri_parts_oqtopus.rest.models.jobs_operator_item import JobsOperatorItem
    from quri_parts_oqtopus.rest.models.jobs_sampling_result import JobsSamplingResult
    from quri_parts_oqtopus.rest.models.jobs_submit_job_info import JobsSubmitJobInfo
    from quri_parts_oqtopus.rest.models.jobs_submit_job_request import JobsSubmitJobRequest
    from quri_parts_oqtopus.rest.models.jobs_submit_job_response import JobsSubmitJobResponse
    from quri_parts_oqtopus.rest.models.jobs_transpile_result import JobsTranspileResult
    from quri_parts_oqtopus.rest.models.success_success_response import SuccessSuccessResponse
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            """# import models into model package
from quri_parts_oqtopus.rest.models.announcements_get_announcement_response import AnnouncementsGetAnnouncementResponse
from quri_parts_oqtopus.rest.models.announcements_get_announcements_list_response import AnnouncementsGetAnnouncementsListResponse
from quri_parts_oqtopus.rest.models.api_token_api_token import ApiTokenApiToken
from quri_parts_oqtopus.rest.models.devices_device_info import DevicesDeviceInfo
from quri_parts_oqtopus.rest.models.error_bad_request import ErrorBadRequest
from quri_parts_oqtopus.rest.models.error_forbidden_error import ErrorForbiddenError
from quri_parts_oqtopus.rest.models.error_internal_server_error import ErrorInternalServerError
from quri_parts_oqtopus.rest.models.error_not_found_error import ErrorNotFoundError
from quri_parts_oqtopus.rest.models.error_unauthorized_error import ErrorUnauthorizedError
from quri_parts_oqtopus.rest.models.jobs_estimation_result import JobsEstimationResult
from quri_parts_oqtopus.rest.models.jobs_get_job_status_response import JobsGetJobStatusResponse
from quri_parts_oqtopus.rest.models.jobs_get_jobs_response import JobsGetJobsResponse
from quri_parts_oqtopus.rest.models.jobs_get_sselog_response import JobsGetSselogResponse
from quri_parts_oqtopus.rest.models.jobs_job_def import JobsJobDef
from quri_parts_oqtopus.rest.models.jobs_job_info import JobsJobInfo
from quri_parts_oqtopus.rest.models.jobs_job_result import JobsJobResult
from quri_parts_oqtopus.rest.models.jobs_job_status import JobsJobStatus
from quri_parts_oqtopus.rest.models.jobs_job_type import JobsJobType
from quri_parts_oqtopus.rest.models.jobs_operator_item import JobsOperatorItem
from quri_parts_oqtopus.rest.models.jobs_sampling_result import JobsSamplingResult
from quri_parts_oqtopus.rest.models.jobs_submit_job_info import JobsSubmitJobInfo
from quri_parts_oqtopus.rest.models.jobs_submit_job_request import JobsSubmitJobRequest
from quri_parts_oqtopus.rest.models.jobs_submit_job_response import JobsSubmitJobResponse
from quri_parts_oqtopus.rest.models.jobs_transpile_result import JobsTranspileResult
from quri_parts_oqtopus.rest.models.success_success_response import SuccessSuccessResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
