# coding: utf-8

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DevicesDeviceInfo(BaseModel):
    """
    DevicesDeviceInfo
    """ # noqa: E501
    device_id: StrictStr
    device_type: StrictStr
    status: StrictStr
    available_at: Optional[datetime] = Field(default=None, description="Parameter mandatory and valid for 'unavailable' devices")
    n_pending_jobs: StrictInt
    n_qubits: Optional[StrictInt] = None
    basis_gates: List[StrictStr]
    supported_instructions: List[StrictStr]
    device_info: Optional[StrictStr] = Field(default=None, description="json format calibration_data and n_nodes etc")
    calibrated_at: Optional[datetime] = Field(default=None, description="Parameter available only for `QPU` devices with available calibration data")
    description: StrictStr
    __properties: ClassVar[List[str]] = ["device_id", "device_type", "status", "available_at", "n_pending_jobs", "n_qubits", "basis_gates", "supported_instructions", "device_info", "calibrated_at", "description"]

    @field_validator('device_type')
    def device_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['QPU', 'simulator']):
            raise ValueError("must be one of enum values ('QPU', 'simulator')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['available', 'unavailable']):
            raise ValueError("must be one of enum values ('available', 'unavailable')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DevicesDeviceInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DevicesDeviceInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "device_id": obj.get("device_id"),
            "device_type": obj.get("device_type"),
            "status": obj.get("status"),
            "available_at": obj.get("available_at"),
            "n_pending_jobs": obj.get("n_pending_jobs"),
            "n_qubits": obj.get("n_qubits"),
            "basis_gates": obj.get("basis_gates"),
            "supported_instructions": obj.get("supported_instructions"),
            "device_info": obj.get("device_info"),
            "calibrated_at": obj.get("calibrated_at"),
            "description": obj.get("description")
        })
        return _obj


