# coding: utf-8

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from quri_parts_oqtopus.rest.models.jobs_submit_job_type import JobsSubmitJobType
from typing import Optional, Set
from typing_extensions import Self

class JobsSubmitJobRequest(BaseModel):
    """
    JobsSubmitJobRequest
    """ # noqa: E501
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    device_id: StrictStr
    job_type: JobsSubmitJobType
    transpiler_info: Optional[Dict[str, Any]] = None
    simulator_info: Optional[Dict[str, Any]] = None
    mitigation_info: Optional[Dict[str, Any]] = None
    shots: Annotated[int, Field(le=10000000, strict=True, ge=1)]
    __properties: ClassVar[List[str]] = ["name", "description", "device_id", "job_type", "transpiler_info", "simulator_info", "mitigation_info", "shots"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobsSubmitJobRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobsSubmitJobRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "device_id": obj.get("device_id"),
            "job_type": obj.get("job_type"),
            "transpiler_info": obj.get("transpiler_info"),
            "simulator_info": obj.get("simulator_info"),
            "mitigation_info": obj.get("mitigation_info"),
            "shots": obj.get("shots")
        })
        return _obj


