# coding: utf-8

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from quri_parts_oqtopus.rest.models.jobs_job_result import JobsJobResult
from quri_parts_oqtopus.rest.models.jobs_operator_item import JobsOperatorItem
from quri_parts_oqtopus.rest.models.jobs_transpile_result import JobsTranspileResult
from typing import Optional, Set
from typing_extensions import Self

class JobsJobInfo(BaseModel):
    """
    JobsJobInfo
    """ # noqa: E501
    program: List[StrictStr] = Field(description="A list of OPENQASM3 program. For non-multiprogramming jobs, this field is assumed to contain exactly one program. Otherwise, those programs are combined according to the multiprogramming machinery.")
    combined_program: Optional[StrictStr] = Field(default=None, description="For multiprogramming jobs, this field contains the combined circuit.")
    operator: Optional[List[JobsOperatorItem]] = Field(default=None, description="*(Only for estimation jobs)* The operator (or observable) for which the expectation value is to be estimated. ")
    result: Optional[JobsJobResult] = None
    transpile_result: Optional[JobsTranspileResult] = None
    message: Optional[StrictStr] = Field(default=None, description="Describing the reason why there is no result")
    __properties: ClassVar[List[str]] = ["program", "combined_program", "operator", "result", "transpile_result", "message"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobsJobInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in operator (list)
        _items = []
        if self.operator:
            for _item_operator in self.operator:
                if _item_operator:
                    _items.append(_item_operator.to_dict())
            _dict['operator'] = _items
        # override the default output from pydantic by calling `to_dict()` of result
        if self.result:
            _dict['result'] = self.result.to_dict()
        # override the default output from pydantic by calling `to_dict()` of transpile_result
        if self.transpile_result:
            _dict['transpile_result'] = self.transpile_result.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobsJobInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "program": obj.get("program"),
            "combined_program": obj.get("combined_program"),
            "operator": [JobsOperatorItem.from_dict(_item) for _item in obj["operator"]] if obj.get("operator") is not None else None,
            "result": JobsJobResult.from_dict(obj["result"]) if obj.get("result") is not None else None,
            "transpile_result": JobsTranspileResult.from_dict(obj["transpile_result"]) if obj.get("transpile_result") is not None else None,
            "message": obj.get("message")
        })
        return _obj


