# coding: utf-8

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from quri_parts_oqtopus.rest.models.jobs_job_info import JobsJobInfo
from quri_parts_oqtopus.rest.models.jobs_job_status import JobsJobStatus
from quri_parts_oqtopus.rest.models.jobs_job_type import JobsJobType
from typing import Optional, Set
from typing_extensions import Self

class JobsJob(BaseModel):
    """
    Represents a quantum job.  Newly registered jobs (status=registered) must provide:    - job_id,    - status (registered)  Fully defined jobs must also provide:   - name   - device_id   - job_type,   - shots   - job_info Other properties and optional and depend on job type and status.
    """ # noqa: E501
    job_id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    job_type: Optional[JobsJobType] = None
    status: Optional[JobsJobStatus] = None
    device_id: Optional[StrictStr] = None
    shots: Optional[Annotated[int, Field(le=10000000, strict=True, ge=1)]] = None
    job_info: Optional[JobsJobInfo] = None
    transpiler_info: Optional[Dict[str, Any]] = None
    simulator_info: Optional[Dict[str, Any]] = None
    mitigation_info: Optional[Dict[str, Any]] = None
    execution_time: Optional[Union[StrictFloat, StrictInt]] = None
    submitted_at: Optional[datetime] = None
    ready_at: Optional[datetime] = None
    running_at: Optional[datetime] = None
    ended_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["job_id", "name", "description", "job_type", "status", "device_id", "shots", "job_info", "transpiler_info", "simulator_info", "mitigation_info", "execution_time", "submitted_at", "ready_at", "running_at", "ended_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobsJob from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of job_info
        if self.job_info:
            _dict['job_info'] = self.job_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobsJob from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_id": obj.get("job_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "job_type": obj.get("job_type"),
            "status": obj.get("status"),
            "device_id": obj.get("device_id"),
            "shots": obj.get("shots"),
            "job_info": JobsJobInfo.from_dict(obj["job_info"]) if obj.get("job_info") is not None else None,
            "transpiler_info": obj.get("transpiler_info"),
            "simulator_info": obj.get("simulator_info"),
            "mitigation_info": obj.get("mitigation_info"),
            "execution_time": obj.get("execution_time"),
            "submitted_at": obj.get("submitted_at"),
            "ready_at": obj.get("ready_at"),
            "running_at": obj.get("running_at"),
            "ended_at": obj.get("ended_at")
        })
        return _obj


