# coding: utf-8

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JobsSubmitJobType(str, Enum):
    """
    JobsSubmitJobType
    """

    """
    allowed enum values
    """
    ESTIMATION = 'estimation'
    SAMPLING = 'sampling'
    MULTI_MANUAL = 'multi_manual'
    SSE = 'sse'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobsSubmitJobType from a JSON string"""
        return cls(json.loads(json_str))


