# coding: utf-8

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class JobsRegisterJobResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'job_id': 'JobsJobId',
        'presigned_url': 'JobsJobInfoUploadPresignedURL'
    }

    attribute_map = {
        'job_id': 'job_id',
        'presigned_url': 'presigned_url'
    }

    def __init__(self, job_id=None, presigned_url=None):  # noqa: E501
        """JobsRegisterJobResponse - a model defined in Swagger"""  # noqa: E501
        self._job_id = None
        self._presigned_url = None
        self.discriminator = None
        self.job_id = job_id
        self.presigned_url = presigned_url

    @property
    def job_id(self):
        """Gets the job_id of this JobsRegisterJobResponse.  # noqa: E501


        :return: The job_id of this JobsRegisterJobResponse.  # noqa: E501
        :rtype: JobsJobId
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """Sets the job_id of this JobsRegisterJobResponse.


        :param job_id: The job_id of this JobsRegisterJobResponse.  # noqa: E501
        :type: JobsJobId
        """
        if job_id is None:
            raise ValueError("Invalid value for `job_id`, must not be `None`")  # noqa: E501

        self._job_id = job_id

    @property
    def presigned_url(self):
        """Gets the presigned_url of this JobsRegisterJobResponse.  # noqa: E501


        :return: The presigned_url of this JobsRegisterJobResponse.  # noqa: E501
        :rtype: JobsJobInfoUploadPresignedURL
        """
        return self._presigned_url

    @presigned_url.setter
    def presigned_url(self, presigned_url):
        """Sets the presigned_url of this JobsRegisterJobResponse.


        :param presigned_url: The presigned_url of this JobsRegisterJobResponse.  # noqa: E501
        :type: JobsJobInfoUploadPresignedURL
        """
        if presigned_url is None:
            raise ValueError("Invalid value for `presigned_url`, must not be `None`")  # noqa: E501

        self._presigned_url = presigned_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JobsRegisterJobResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JobsRegisterJobResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
