# coding: utf-8

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class SettingsGetSettingsResponse(BaseModel):
    """
    detail of settings response
    """ # noqa: E501
    editable_fields: List[StrictStr]
    allow_deletion: StrictBool
    visible_fields: List[StrictStr]
    login_history_enabled: StrictBool
    __properties: ClassVar[List[str]] = ["editable_fields", "allow_deletion", "visible_fields", "login_history_enabled"]

    @field_validator('editable_fields')
    def editable_fields_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['name', 'organization']):
                raise ValueError("each list item must be one of ('name', 'organization')")
        return value

    @field_validator('visible_fields')
    def visible_fields_validate_enum(cls, value):
        """Validates the enum"""
        for i in value:
            if i not in set(['id', 'name', 'email', 'organization', 'created_at']):
                raise ValueError("each list item must be one of ('id', 'name', 'email', 'organization', 'created_at')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SettingsGetSettingsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SettingsGetSettingsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "editable_fields": obj.get("editable_fields"),
            "allow_deletion": obj.get("allow_deletion"),
            "visible_fields": obj.get("visible_fields"),
            "login_history_enabled": obj.get("login_history_enabled")
        })
        return _obj


