# coding: utf-8

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from quri_parts_oqtopus.rest.models.users_login_event import UsersLoginEvent
from typing import Optional, Set
from typing_extensions import Self

class UsersGetOneUserResponse(BaseModel):
    """
    detail of user response
    """ # noqa: E501
    id: Optional[StrictInt] = None
    email: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    organization: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    login_events: Optional[List[UsersLoginEvent]] = None
    __properties: ClassVar[List[str]] = ["id", "email", "name", "organization", "created_at", "login_events"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsersGetOneUserResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in login_events (list)
        _items = []
        if self.login_events:
            for _item_login_events in self.login_events:
                if _item_login_events:
                    _items.append(_item_login_events.to_dict())
            _dict['login_events'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsersGetOneUserResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "email": obj.get("email"),
            "name": obj.get("name"),
            "organization": obj.get("organization"),
            "created_at": obj.get("created_at"),
            "login_events": [UsersLoginEvent.from_dict(_item) for _item in obj["login_events"]] if obj.get("login_events") is not None else None
        })
        return _obj


