# coding: utf-8

# flake8: noqa

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AnnouncementsApi",
    "ApiTokenApi",
    "DeviceApi",
    "JobApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AnnouncementsGetAnnouncementResponse",
    "AnnouncementsGetAnnouncementsListResponse",
    "ApiTokenApiToken",
    "DevicesDeviceInfo",
    "ErrorBadRequest",
    "ErrorForbiddenError",
    "ErrorInternalServerError",
    "ErrorNotFoundError",
    "ErrorUnauthorizedError",
    "JobsEstimationResult",
    "JobsGetJobStatusResponse",
    "JobsGetJobsResponse",
    "JobsGetSselogResponse",
    "JobsJobDef",
    "JobsJobInfo",
    "JobsJobResult",
    "JobsJobStatus",
    "JobsJobType",
    "JobsOperatorItem",
    "JobsSamplingResult",
    "JobsSubmitJobInfo",
    "JobsSubmitJobRequest",
    "JobsSubmitJobResponse",
    "JobsTranspileResult",
    "SuccessSuccessResponse",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from quri_parts_oqtopus.rest.api.announcements_api import AnnouncementsApi as AnnouncementsApi
    from quri_parts_oqtopus.rest.api.api_token_api import ApiTokenApi as ApiTokenApi
    from quri_parts_oqtopus.rest.api.device_api import DeviceApi as DeviceApi
    from quri_parts_oqtopus.rest.api.job_api import JobApi as JobApi
    
    # import ApiClient
    from quri_parts_oqtopus.rest.api_response import ApiResponse as ApiResponse
    from quri_parts_oqtopus.rest.api_client import ApiClient as ApiClient
    from quri_parts_oqtopus.rest.configuration import Configuration as Configuration
    from quri_parts_oqtopus.rest.exceptions import OpenApiException as OpenApiException
    from quri_parts_oqtopus.rest.exceptions import ApiTypeError as ApiTypeError
    from quri_parts_oqtopus.rest.exceptions import ApiValueError as ApiValueError
    from quri_parts_oqtopus.rest.exceptions import ApiKeyError as ApiKeyError
    from quri_parts_oqtopus.rest.exceptions import ApiAttributeError as ApiAttributeError
    from quri_parts_oqtopus.rest.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from quri_parts_oqtopus.rest.models.announcements_get_announcement_response import AnnouncementsGetAnnouncementResponse as AnnouncementsGetAnnouncementResponse
    from quri_parts_oqtopus.rest.models.announcements_get_announcements_list_response import AnnouncementsGetAnnouncementsListResponse as AnnouncementsGetAnnouncementsListResponse
    from quri_parts_oqtopus.rest.models.api_token_api_token import ApiTokenApiToken as ApiTokenApiToken
    from quri_parts_oqtopus.rest.models.devices_device_info import DevicesDeviceInfo as DevicesDeviceInfo
    from quri_parts_oqtopus.rest.models.error_bad_request import ErrorBadRequest as ErrorBadRequest
    from quri_parts_oqtopus.rest.models.error_forbidden_error import ErrorForbiddenError as ErrorForbiddenError
    from quri_parts_oqtopus.rest.models.error_internal_server_error import ErrorInternalServerError as ErrorInternalServerError
    from quri_parts_oqtopus.rest.models.error_not_found_error import ErrorNotFoundError as ErrorNotFoundError
    from quri_parts_oqtopus.rest.models.error_unauthorized_error import ErrorUnauthorizedError as ErrorUnauthorizedError
    from quri_parts_oqtopus.rest.models.jobs_estimation_result import JobsEstimationResult as JobsEstimationResult
    from quri_parts_oqtopus.rest.models.jobs_get_job_status_response import JobsGetJobStatusResponse as JobsGetJobStatusResponse
    from quri_parts_oqtopus.rest.models.jobs_get_jobs_response import JobsGetJobsResponse as JobsGetJobsResponse
    from quri_parts_oqtopus.rest.models.jobs_get_sselog_response import JobsGetSselogResponse as JobsGetSselogResponse
    from quri_parts_oqtopus.rest.models.jobs_job_def import JobsJobDef as JobsJobDef
    from quri_parts_oqtopus.rest.models.jobs_job_info import JobsJobInfo as JobsJobInfo
    from quri_parts_oqtopus.rest.models.jobs_job_result import JobsJobResult as JobsJobResult
    from quri_parts_oqtopus.rest.models.jobs_job_status import JobsJobStatus as JobsJobStatus
    from quri_parts_oqtopus.rest.models.jobs_job_type import JobsJobType as JobsJobType
    from quri_parts_oqtopus.rest.models.jobs_operator_item import JobsOperatorItem as JobsOperatorItem
    from quri_parts_oqtopus.rest.models.jobs_sampling_result import JobsSamplingResult as JobsSamplingResult
    from quri_parts_oqtopus.rest.models.jobs_submit_job_info import JobsSubmitJobInfo as JobsSubmitJobInfo
    from quri_parts_oqtopus.rest.models.jobs_submit_job_request import JobsSubmitJobRequest as JobsSubmitJobRequest
    from quri_parts_oqtopus.rest.models.jobs_submit_job_response import JobsSubmitJobResponse as JobsSubmitJobResponse
    from quri_parts_oqtopus.rest.models.jobs_transpile_result import JobsTranspileResult as JobsTranspileResult
    from quri_parts_oqtopus.rest.models.success_success_response import SuccessSuccessResponse as SuccessSuccessResponse
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from quri_parts_oqtopus.rest.api.announcements_api import AnnouncementsApi as AnnouncementsApi
from quri_parts_oqtopus.rest.api.api_token_api import ApiTokenApi as ApiTokenApi
from quri_parts_oqtopus.rest.api.device_api import DeviceApi as DeviceApi
from quri_parts_oqtopus.rest.api.job_api import JobApi as JobApi

# import ApiClient
from quri_parts_oqtopus.rest.api_response import ApiResponse as ApiResponse
from quri_parts_oqtopus.rest.api_client import ApiClient as ApiClient
from quri_parts_oqtopus.rest.configuration import Configuration as Configuration
from quri_parts_oqtopus.rest.exceptions import OpenApiException as OpenApiException
from quri_parts_oqtopus.rest.exceptions import ApiTypeError as ApiTypeError
from quri_parts_oqtopus.rest.exceptions import ApiValueError as ApiValueError
from quri_parts_oqtopus.rest.exceptions import ApiKeyError as ApiKeyError
from quri_parts_oqtopus.rest.exceptions import ApiAttributeError as ApiAttributeError
from quri_parts_oqtopus.rest.exceptions import ApiException as ApiException

# import models into sdk package
from quri_parts_oqtopus.rest.models.announcements_get_announcement_response import AnnouncementsGetAnnouncementResponse as AnnouncementsGetAnnouncementResponse
from quri_parts_oqtopus.rest.models.announcements_get_announcements_list_response import AnnouncementsGetAnnouncementsListResponse as AnnouncementsGetAnnouncementsListResponse
from quri_parts_oqtopus.rest.models.api_token_api_token import ApiTokenApiToken as ApiTokenApiToken
from quri_parts_oqtopus.rest.models.devices_device_info import DevicesDeviceInfo as DevicesDeviceInfo
from quri_parts_oqtopus.rest.models.error_bad_request import ErrorBadRequest as ErrorBadRequest
from quri_parts_oqtopus.rest.models.error_forbidden_error import ErrorForbiddenError as ErrorForbiddenError
from quri_parts_oqtopus.rest.models.error_internal_server_error import ErrorInternalServerError as ErrorInternalServerError
from quri_parts_oqtopus.rest.models.error_not_found_error import ErrorNotFoundError as ErrorNotFoundError
from quri_parts_oqtopus.rest.models.error_unauthorized_error import ErrorUnauthorizedError as ErrorUnauthorizedError
from quri_parts_oqtopus.rest.models.jobs_estimation_result import JobsEstimationResult as JobsEstimationResult
from quri_parts_oqtopus.rest.models.jobs_get_job_status_response import JobsGetJobStatusResponse as JobsGetJobStatusResponse
from quri_parts_oqtopus.rest.models.jobs_get_jobs_response import JobsGetJobsResponse as JobsGetJobsResponse
from quri_parts_oqtopus.rest.models.jobs_get_sselog_response import JobsGetSselogResponse as JobsGetSselogResponse
from quri_parts_oqtopus.rest.models.jobs_job_def import JobsJobDef as JobsJobDef
from quri_parts_oqtopus.rest.models.jobs_job_info import JobsJobInfo as JobsJobInfo
from quri_parts_oqtopus.rest.models.jobs_job_result import JobsJobResult as JobsJobResult
from quri_parts_oqtopus.rest.models.jobs_job_status import JobsJobStatus as JobsJobStatus
from quri_parts_oqtopus.rest.models.jobs_job_type import JobsJobType as JobsJobType
from quri_parts_oqtopus.rest.models.jobs_operator_item import JobsOperatorItem as JobsOperatorItem
from quri_parts_oqtopus.rest.models.jobs_sampling_result import JobsSamplingResult as JobsSamplingResult
from quri_parts_oqtopus.rest.models.jobs_submit_job_info import JobsSubmitJobInfo as JobsSubmitJobInfo
from quri_parts_oqtopus.rest.models.jobs_submit_job_request import JobsSubmitJobRequest as JobsSubmitJobRequest
from quri_parts_oqtopus.rest.models.jobs_submit_job_response import JobsSubmitJobResponse as JobsSubmitJobResponse
from quri_parts_oqtopus.rest.models.jobs_transpile_result import JobsTranspileResult as JobsTranspileResult
from quri_parts_oqtopus.rest.models.success_success_response import SuccessSuccessResponse as SuccessSuccessResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
