# coding: utf-8

# flake8: noqa

"""
    OQTOPUS Cloud User API

    OQTOPUS Cloud User API. This API is used to interact with the OQTOPUS Cloud service. The API provides endpoints to manage devices, jobs, and results.

    The version of the OpenAPI document: 1.0
    Contact: oqtopus-team[at]googlegroups.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "AnnouncementsApi",
    "ApiTokenApi",
    "DeviceApi",
    "JobApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AnnouncementsGetAnnouncementResponse",
    "AnnouncementsGetAnnouncementsListResponse",
    "ApiTokenApiToken",
    "DevicesDeviceInfo",
    "ErrorBadRequest",
    "ErrorForbiddenError",
    "ErrorInternalServerError",
    "ErrorNotFoundError",
    "ErrorUnauthorizedError",
    "JobsGetJobStatusResponse",
    "JobsJob",
    "JobsJobInfo",
    "JobsJobInfoUploadPresignedURL",
    "JobsJobInfoUploadPresignedURLFields",
    "JobsJobStatus",
    "JobsJobType",
    "JobsRegisterJobResponse",
    "JobsRegisteredJob",
    "JobsS3EstimationResult",
    "JobsS3JobResult",
    "JobsS3OperatorItem",
    "JobsS3SamplingResult",
    "JobsS3SubmitJobInfo",
    "JobsS3TranspileResult",
    "JobsSubmitJobRequest",
    "JobsSubmittedJob",
    "SuccessSuccessResponse",
]

if __import__("typing").TYPE_CHECKING:
    # import apis into sdk package
    from quri_parts_oqtopus.rest.api.announcements_api import AnnouncementsApi as AnnouncementsApi
    from quri_parts_oqtopus.rest.api.api_token_api import ApiTokenApi as ApiTokenApi
    from quri_parts_oqtopus.rest.api.device_api import DeviceApi as DeviceApi
    from quri_parts_oqtopus.rest.api.job_api import JobApi as JobApi
    
    # import ApiClient
    from quri_parts_oqtopus.rest.api_response import ApiResponse as ApiResponse
    from quri_parts_oqtopus.rest.api_client import ApiClient as ApiClient
    from quri_parts_oqtopus.rest.configuration import Configuration as Configuration
    from quri_parts_oqtopus.rest.exceptions import OpenApiException as OpenApiException
    from quri_parts_oqtopus.rest.exceptions import ApiTypeError as ApiTypeError
    from quri_parts_oqtopus.rest.exceptions import ApiValueError as ApiValueError
    from quri_parts_oqtopus.rest.exceptions import ApiKeyError as ApiKeyError
    from quri_parts_oqtopus.rest.exceptions import ApiAttributeError as ApiAttributeError
    from quri_parts_oqtopus.rest.exceptions import ApiException as ApiException
    
    # import models into sdk package
    from quri_parts_oqtopus.rest.models.announcements_get_announcement_response import AnnouncementsGetAnnouncementResponse as AnnouncementsGetAnnouncementResponse
    from quri_parts_oqtopus.rest.models.announcements_get_announcements_list_response import AnnouncementsGetAnnouncementsListResponse as AnnouncementsGetAnnouncementsListResponse
    from quri_parts_oqtopus.rest.models.api_token_api_token import ApiTokenApiToken as ApiTokenApiToken
    from quri_parts_oqtopus.rest.models.devices_device_info import DevicesDeviceInfo as DevicesDeviceInfo
    from quri_parts_oqtopus.rest.models.error_bad_request import ErrorBadRequest as ErrorBadRequest
    from quri_parts_oqtopus.rest.models.error_forbidden_error import ErrorForbiddenError as ErrorForbiddenError
    from quri_parts_oqtopus.rest.models.error_internal_server_error import ErrorInternalServerError as ErrorInternalServerError
    from quri_parts_oqtopus.rest.models.error_not_found_error import ErrorNotFoundError as ErrorNotFoundError
    from quri_parts_oqtopus.rest.models.error_unauthorized_error import ErrorUnauthorizedError as ErrorUnauthorizedError
    from quri_parts_oqtopus.rest.models.jobs_get_job_status_response import JobsGetJobStatusResponse as JobsGetJobStatusResponse
    from quri_parts_oqtopus.rest.models.jobs_job import JobsJob as JobsJob
    from quri_parts_oqtopus.rest.models.jobs_job_info import JobsJobInfo as JobsJobInfo
    from quri_parts_oqtopus.rest.models.jobs_job_info_upload_presigned_url import JobsJobInfoUploadPresignedURL as JobsJobInfoUploadPresignedURL
    from quri_parts_oqtopus.rest.models.jobs_job_info_upload_presigned_url_fields import JobsJobInfoUploadPresignedURLFields as JobsJobInfoUploadPresignedURLFields
    from quri_parts_oqtopus.rest.models.jobs_job_status import JobsJobStatus as JobsJobStatus
    from quri_parts_oqtopus.rest.models.jobs_job_type import JobsJobType as JobsJobType
    from quri_parts_oqtopus.rest.models.jobs_register_job_response import JobsRegisterJobResponse as JobsRegisterJobResponse
    from quri_parts_oqtopus.rest.models.jobs_registered_job import JobsRegisteredJob as JobsRegisteredJob
    from quri_parts_oqtopus.rest.models.jobs_s3_estimation_result import JobsS3EstimationResult as JobsS3EstimationResult
    from quri_parts_oqtopus.rest.models.jobs_s3_job_result import JobsS3JobResult as JobsS3JobResult
    from quri_parts_oqtopus.rest.models.jobs_s3_operator_item import JobsS3OperatorItem as JobsS3OperatorItem
    from quri_parts_oqtopus.rest.models.jobs_s3_sampling_result import JobsS3SamplingResult as JobsS3SamplingResult
    from quri_parts_oqtopus.rest.models.jobs_s3_submit_job_info import JobsS3SubmitJobInfo as JobsS3SubmitJobInfo
    from quri_parts_oqtopus.rest.models.jobs_s3_transpile_result import JobsS3TranspileResult as JobsS3TranspileResult
    from quri_parts_oqtopus.rest.models.jobs_submit_job_request import JobsSubmitJobRequest as JobsSubmitJobRequest
    from quri_parts_oqtopus.rest.models.jobs_submitted_job import JobsSubmittedJob as JobsSubmittedJob
    from quri_parts_oqtopus.rest.models.success_success_response import SuccessSuccessResponse as SuccessSuccessResponse
    
else:
    from lazy_imports import LazyModule, as_package, load

    load(
        LazyModule(
            *as_package(__file__),
            ("__version__", __version__),
            ("__all__", __all__),
            """# import apis into sdk package
from quri_parts_oqtopus.rest.api.announcements_api import AnnouncementsApi as AnnouncementsApi
from quri_parts_oqtopus.rest.api.api_token_api import ApiTokenApi as ApiTokenApi
from quri_parts_oqtopus.rest.api.device_api import DeviceApi as DeviceApi
from quri_parts_oqtopus.rest.api.job_api import JobApi as JobApi

# import ApiClient
from quri_parts_oqtopus.rest.api_response import ApiResponse as ApiResponse
from quri_parts_oqtopus.rest.api_client import ApiClient as ApiClient
from quri_parts_oqtopus.rest.configuration import Configuration as Configuration
from quri_parts_oqtopus.rest.exceptions import OpenApiException as OpenApiException
from quri_parts_oqtopus.rest.exceptions import ApiTypeError as ApiTypeError
from quri_parts_oqtopus.rest.exceptions import ApiValueError as ApiValueError
from quri_parts_oqtopus.rest.exceptions import ApiKeyError as ApiKeyError
from quri_parts_oqtopus.rest.exceptions import ApiAttributeError as ApiAttributeError
from quri_parts_oqtopus.rest.exceptions import ApiException as ApiException

# import models into sdk package
from quri_parts_oqtopus.rest.models.announcements_get_announcement_response import AnnouncementsGetAnnouncementResponse as AnnouncementsGetAnnouncementResponse
from quri_parts_oqtopus.rest.models.announcements_get_announcements_list_response import AnnouncementsGetAnnouncementsListResponse as AnnouncementsGetAnnouncementsListResponse
from quri_parts_oqtopus.rest.models.api_token_api_token import ApiTokenApiToken as ApiTokenApiToken
from quri_parts_oqtopus.rest.models.devices_device_info import DevicesDeviceInfo as DevicesDeviceInfo
from quri_parts_oqtopus.rest.models.error_bad_request import ErrorBadRequest as ErrorBadRequest
from quri_parts_oqtopus.rest.models.error_forbidden_error import ErrorForbiddenError as ErrorForbiddenError
from quri_parts_oqtopus.rest.models.error_internal_server_error import ErrorInternalServerError as ErrorInternalServerError
from quri_parts_oqtopus.rest.models.error_not_found_error import ErrorNotFoundError as ErrorNotFoundError
from quri_parts_oqtopus.rest.models.error_unauthorized_error import ErrorUnauthorizedError as ErrorUnauthorizedError
from quri_parts_oqtopus.rest.models.jobs_get_job_status_response import JobsGetJobStatusResponse as JobsGetJobStatusResponse
from quri_parts_oqtopus.rest.models.jobs_job import JobsJob as JobsJob
from quri_parts_oqtopus.rest.models.jobs_job_info import JobsJobInfo as JobsJobInfo
from quri_parts_oqtopus.rest.models.jobs_job_info_upload_presigned_url import JobsJobInfoUploadPresignedURL as JobsJobInfoUploadPresignedURL
from quri_parts_oqtopus.rest.models.jobs_job_info_upload_presigned_url_fields import JobsJobInfoUploadPresignedURLFields as JobsJobInfoUploadPresignedURLFields
from quri_parts_oqtopus.rest.models.jobs_job_status import JobsJobStatus as JobsJobStatus
from quri_parts_oqtopus.rest.models.jobs_job_type import JobsJobType as JobsJobType
from quri_parts_oqtopus.rest.models.jobs_register_job_response import JobsRegisterJobResponse as JobsRegisterJobResponse
from quri_parts_oqtopus.rest.models.jobs_registered_job import JobsRegisteredJob as JobsRegisteredJob
from quri_parts_oqtopus.rest.models.jobs_s3_estimation_result import JobsS3EstimationResult as JobsS3EstimationResult
from quri_parts_oqtopus.rest.models.jobs_s3_job_result import JobsS3JobResult as JobsS3JobResult
from quri_parts_oqtopus.rest.models.jobs_s3_operator_item import JobsS3OperatorItem as JobsS3OperatorItem
from quri_parts_oqtopus.rest.models.jobs_s3_sampling_result import JobsS3SamplingResult as JobsS3SamplingResult
from quri_parts_oqtopus.rest.models.jobs_s3_submit_job_info import JobsS3SubmitJobInfo as JobsS3SubmitJobInfo
from quri_parts_oqtopus.rest.models.jobs_s3_transpile_result import JobsS3TranspileResult as JobsS3TranspileResult
from quri_parts_oqtopus.rest.models.jobs_submit_job_request import JobsSubmitJobRequest as JobsSubmitJobRequest
from quri_parts_oqtopus.rest.models.jobs_submitted_job import JobsSubmittedJob as JobsSubmittedJob
from quri_parts_oqtopus.rest.models.success_success_response import SuccessSuccessResponse as SuccessSuccessResponse

""",
            name=__name__,
            doc=__doc__,
        )
    )
