import base64
from pathlib import Path

from quri_parts.backend import (
    BackendError,
)

from quri_parts_oqtopus.models.jobs.base import OqtopusJobBase
from quri_parts_oqtopus.models.jobs.results.sampling import (
    OqtopusSamplingResult,
)
from quri_parts_oqtopus.models.jobs.sampling import OqtopusSamplingJob
from quri_parts_oqtopus.rest import (
    JobApi,
    JobsJobDef,
)

JOB_FINAL_STATUS = ["succeeded", "failed", "cancelled"]


class OqtopusSseJob(OqtopusJobBase):
    """A job for a SSE.

    Args:
        job: A result of dict type.
        job_api: A result of dict type.

    Raises:
        ValueError: If ``job`` or ``job_api`` is None.

    """

    def __init__(self, job: JobsJobDef, job_api: JobApi) -> None:
        super().__init__(job=job, job_api=job_api)

    def result(
        self, timeout: float | None = None, wait: float = 10.0
    ) -> OqtopusSamplingResult:
        """Wait until the job progress to the end and returns the result of the job.

        If the status of job is not ``succeeded`` or ``failed``, or ``cancelled``,
        the job is retrieved from OQTOPUS Cloud at intervals of ``wait`` seconds.
        If the job does not progress to the end after ``timeout`` seconds,
        raise :class:`BackendError`.

        Args:
            timeout: The number of seconds to wait for job.
            wait: Time in seconds between queries.

        Returns:
            OqtopusSamplingResult: the result of the sampling job.

        Raises:
            BackendError: If job cannot be found or if an authentication error occurred
                or timeout occurs, etc.

        """
        try:
            sampling_job = OqtopusSamplingJob(job=self._job, job_api=self._job_api)
        except BackendError as e:
            msg = f"Failed to create OqtopusSamplingJob: {e}"
            raise BackendError(msg) from e

        return sampling_job.result(timeout=timeout, wait=wait)

    def download_log(
        self,
        save_dir: str | None = None,
    ) -> str:
        """Download logs generated by an SSE job on a OQTOPUS Cloud.

        Args:
            save_dir (str | None, optional): Local directory path for downloads.
                Defaults to None.

        Raises:
            BackendError: If an error is returned from OQTOPUS Cloud.
            ValueError: If ``save_dir`` does not exist.
            ValueError: If ``save_dir`` is not a directory.
            ValueError: If the file already exists.

        Returns:
            str: The file path of the saved SSE log.

        """
        try:
            response = self._job_api.get_sselog(job_id=self._job.job_id)
        except Exception as e:
            msg = "To perform sse on OQTOPUS Cloud is failed."
            raise BackendError(msg) from e

        if response is None or not response.file or not response.file_name:
            msg = (
                "To perform sse on OQTOPUS Cloud is failed."
                " The response does not contain valid file data."
            )
            raise BackendError(msg)

        data = response.file
        file_name = response.file_name

        if save_dir is None:
            path_save_dir = Path.cwd()
        elif not Path(save_dir).exists():
            msg = f"The destination path does not exist: {save_dir}"
            raise ValueError(msg)
        elif not Path(save_dir).is_dir():
            msg = f"The destination path is not a directory: {save_dir}"
            raise ValueError(msg)
        else:
            path_save_dir = Path(save_dir)

        file_path = path_save_dir / file_name
        # if the file already exists, raise ValueError
        if Path(file_path).exists():
            msg = f"The file already exists: {file_path}"
            raise ValueError(msg)

        # decode the base64 encoded data and write it to the file
        decoded_zip = base64.b64decode(data)
        with Path(file_path).open(mode="bw") as t_file:
            t_file.write(decoded_zip)

        return str(file_path)

    def __repr__(self) -> str:
        """Return a string representation of the OqtopusSseJob.

        Returns:
            str: A string representation of the OqtopusSseJob.

        """
        return self._job.to_str()
