name: Release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    permissions:
      contents: write
      id-token: write
    environment:
      name: pypi
    steps:
      # ----------------------------
      # Setup
      # ----------------------------
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.0.0
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"
          cache-python: true
          python-version: 3.13

      - name: Set up Python
        run: uv python install

      # ----------------------------
      # Build
      # ----------------------------
      - name: Build
        run: uv build

      # ----------------------------
      # Create GitHub Release
      # ----------------------------
      - name: Create GitHub Release
        run: |
          gh release create "${VERSION}" --title "${VERSION}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ----------------------------
      # Publish to PyPI
      # ----------------------------
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
